[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "crispr-offtarget-cas12-cas9-engine"
version = "2.0.0"
description = "CRISPR-Scan Pro: Cas9 / Cas12a CFD Score & Off-Target Cutting Predictor"
readme = "README.md"
authors = [{ name = "Dr. Abu Suraih Sakhri", email = "abusuraih@example.com" }]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Security/Cryptography",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
requires-python = ">=3.9"
dependencies = []

[project.scripts]
crispr-offtarget-cas12-cas9-engine = "crispr_offtarget_scan.cli:main"

[project.urls]
Homepage = "https://github.com/abusuraihsakhri/crispr-offtarget-cas12-cas9-engine"
Repository = "https://github.com/abusuraihsakhri/crispr-offtarget-cas12-cas9-engine.git"
